# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-18 15:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='liked_by', to='posts.Post'),
        ),
    ]
